# Generated by Django 5.0.3 on 2024-04-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
